name: inventory_keeper
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2
  cloud_firestore: ^3.1.13
  firebase_core: ^1.15.0
  get_it: ^7.2.0
  uuid: ^3.0.6
  intl: ^0.17.0
  fake_cloud_firestore: ^1.2.2
  grouped_list: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  very_good_analysis: ^2.4.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/


